import { expect, test } from '@playwright/test';
import { enterCampusAt } from './helpers/campus';

test('开始校园跑切换专属音乐，退出恢复背景音乐并保留音量和暂停选择', async ({ page }) => {
  await enterCampusAt(page, 425, 934);
  await page.keyboard.press('KeyE');
  await page.getByRole('tab', { name: '校园跑', exact: true }).click();
  const audio = page.locator('audio[loop]');
  await expect(audio).toHaveAttribute('src', /campus-background\.mp3$/);
  await page.getByRole('button', { name: '开始校园跑', exact: true }).click();
  await expect(audio).toHaveAttribute('src', /campus-run\.mp3$/);
  await expect.poll(() => audio.evaluate((el: HTMLAudioElement) => !el.paused && el.currentTime > 0)).toBe(true);
  await expect(audio).toHaveCount(1);
  await page.getByRole('button', { name: '背景音乐设置' }).click();
  await expect(page.getByRole('heading', { name: '校园跑音乐', exact: true })).toBeVisible();
  await page.getByRole('slider', { name: '音乐音量' }).fill('31');
  await page.getByRole('button', { name: '静音', exact: true }).click();
  await page.getByRole('button', { name: '暂停音乐' }).click();
  await page.getByRole('button', { name: '关闭背景音乐' }).click();
  await page.getByRole('tab', { name: '社团目录', exact: true }).click();
  await expect(audio).toHaveAttribute('src', /campus-background\.mp3$/);
  expect(await audio.evaluate((el: HTMLAudioElement) => ({ paused: el.paused, volume: el.volume, muted: el.muted }))).toEqual({ paused: true, volume: 0.31, muted: true });
  await page.getByRole('tab', { name: '校园跑', exact: true }).click();
  await page.getByRole('button', { name: '开始校园跑', exact: true }).click();
  await expect(audio).toHaveAttribute('src', /campus-run\.mp3$/);
  expect(await audio.evaluate((el: HTMLAudioElement) => el.paused)).toBe(true);
  await page.getByRole('button', { name: '背景音乐设置' }).click();
  await page.getByRole('button', { name: '取消静音' }).click();
  await page.getByRole('button', { name: '播放音乐' }).click();
  await expect.poll(() => audio.evaluate((el: HTMLAudioElement) => !el.paused)).toBe(true);
  await page.getByRole('button', { name: '关闭背景音乐' }).click();
  await page.getByRole('button', { name: '返回校园', exact: true }).click();
  await expect(audio).toHaveAttribute('src', /campus-background\.mp3$/);
  await expect.poll(() => audio.evaluate((el: HTMLAudioElement) => !el.paused && el.currentTime > 0)).toBe(true);
});

test('音乐在首页、校园、功能页之间持续播放，音量和静音在刷新后保留', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/');
  await page.getByRole('button', { name: '背景音乐', exact: true }).click();
  const slider = page.getByRole('slider', { name: '音乐音量' });
  await expect(slider).toBeVisible();
  const audio = page.locator('audio[loop]');
  await expect(audio).toHaveCount(1);
  await expect.poll(() => audio.evaluate((el: HTMLAudioElement) => !el.paused && el.currentTime > 0)).toBe(true);
  await slider.fill('23');
  await expect.poll(() => audio.evaluate((el: HTMLAudioElement) => el.volume)).toBe(0.23);
  await page.getByRole('button', { name: '关闭背景音乐' }).click();
  const original = await audio.elementHandle();
  const before = await audio.evaluate((el: HTMLAudioElement) => el.currentTime);
  await page.getByRole('button', { name: '进入校园', exact: true }).click();
  await expect(page.getByRole('status', { name: '地图加载状态' })).toHaveText('地图已加载');
  for (const hash of ['#teaching', '#dormitory', '#scenes', '']) {
    await page.evaluate(hash => { history.pushState({}, '', location.pathname + hash); dispatchEvent(new PopStateEvent('popstate')); }, hash);
    await expect(page.getByRole('button', { name: '背景音乐设置' })).toBeVisible();
    expect(await original!.evaluate(el => el === document.querySelector('audio[loop]'))).toBe(true);
    await expect.poll(() => audio.evaluate((el: HTMLAudioElement) => !el.paused && el.currentTime > 0)).toBe(true);
  }
  expect(await audio.evaluate((el: HTMLAudioElement) => el.currentTime)).toBeGreaterThan(before);
  await page.getByRole('button', { name: '背景音乐设置' }).click();
  await page.getByRole('button', { name: '静音', exact: true }).click();
  expect(await audio.evaluate((el: HTMLAudioElement) => el.muted)).toBe(true);
  await page.reload();
  await page.getByRole('button', { name: '背景音乐', exact: true }).click();
  await expect(slider).toHaveValue('23');
  await expect(page.getByRole('button', { name: '取消静音' })).toBeVisible();
  await page.getByRole('button', { name: '取消静音' }).click();
  expect(await audio.evaluate((el: HTMLAudioElement) => el.muted)).toBe(false);
  await page.getByRole('button', { name: '暂停音乐' }).click();
  await page.getByRole('button', { name: '关闭背景音乐' }).click();
  await page.getByRole('button', { name: '进入校园', exact: true }).click();
  expect(await audio.evaluate((el: HTMLAudioElement) => el.paused)).toBe(true);
  await page.getByRole('button', { name: '背景音乐设置' }).click();
  await page.getByRole('button', { name: '播放音乐' }).click();
  await expect.poll(() => audio.evaluate((el: HTMLAudioElement) => !el.paused)).toBe(true);
  expect(await audio.evaluate((el: HTMLAudioElement) => el.loop)).toBe(true);
  await page.screenshot({ path: 'output/music-controls.png' });
  expect(errors).toEqual([]);
});

test('手机音量面板可操作，曲目结束后自动循环', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto('/');
  await page.getByRole('button', { name: '背景音乐', exact: true }).click();
  const audio = page.locator('audio[loop]');
  await expect.poll(() => audio.evaluate((el: HTMLAudioElement) => Number.isFinite(el.duration) && !el.paused)).toBe(true);
  const slider = page.getByRole('slider', { name: '音乐音量' });
  await slider.fill('0');
  expect(await audio.evaluate((el: HTMLAudioElement) => el.volume)).toBe(0);
  await slider.fill('100');
  expect(await audio.evaluate((el: HTMLAudioElement) => el.volume)).toBe(1);
  await audio.evaluate((el: HTMLAudioElement) => { el.currentTime = el.duration - 0.3; });
  await expect.poll(() => audio.evaluate((el: HTMLAudioElement) => el.currentTime < 3 && !el.paused)).toBe(true);
  const bounds = await page.getByRole('dialog').boundingBox();
  expect(bounds!.x).toBeGreaterThanOrEqual(0);
  expect(bounds!.x + bounds!.width).toBeLessThanOrEqual(390);
  await page.screenshot({ path: 'output/music-controls-mobile.png' });
});
