import { expect, test } from '@playwright/test';
import { enterCampusAt } from './helpers/campus';

test('骑行经过强制下车并持续拦停，点击语言框才放行；步行不触发', async ({ page }, testInfo) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await enterCampusAt(page, 335, 419);
  const reminder = page.getByRole('button', { name: '同学停下！！！头盔！！！！', exact: true });
  await page.keyboard.down('KeyD');
  await page.waitForTimeout(100);
  await page.keyboard.up('KeyD');
  await expect(reminder).toBeHidden();
  await page.keyboard.down('Shift');
  await page.waitForTimeout(150);
  await expect(reminder).toBeHidden();
  await page.keyboard.down('KeyD');
  await expect(reminder).toBeVisible();
  const status = page.getByTestId('character-status');
  await expect(status).toContainText('步行');
  const stopped = await status.textContent();
  await page.waitForTimeout(4200);
  await expect(reminder).toBeVisible();
  await expect(status).toHaveText(stopped!);
  await page.keyboard.up('KeyD');
  await page.keyboard.up('Shift');
  await page.screenshot({ path: testInfo.outputPath('south-gate-helmet-reminder.png') });
  await page.keyboard.down('KeyA');
  await page.waitForTimeout(200);
  await expect(status).toHaveText(stopped!);
  await page.keyboard.up('KeyA');
  await reminder.click();
  await expect(reminder).toBeHidden();
  await page.keyboard.down('Shift');
  await page.keyboard.down('KeyA');
  await page.waitForTimeout(100);
  await page.keyboard.up('KeyA');
  await page.keyboard.up('Shift');
  await expect(status).not.toHaveText(stopped!);
  await expect(reminder).toBeHidden();
  expect(errors).toEqual([]);
});

test('离开再经过会重新拦停；查看地图不能绕过点击放行', async ({ page }) => {
  await enterCampusAt(page, 335, 480);
  const reminder = page.getByRole('button', { name: '同学停下！！！头盔！！！！', exact: true });
  const y = async () => Number((await page.getByTestId('character-status').textContent())?.match(/位置 [\d.]+, ([\d.]+)/)?.[1]);
  await page.keyboard.down('Shift');
  await expect(reminder).toBeHidden();
  await page.keyboard.down('KeyW');
  await expect(reminder).toBeVisible();
  await page.keyboard.up('KeyW');
  await page.keyboard.up('Shift');
  await reminder.click();
  await page.keyboard.down('Shift');
  await page.keyboard.down('KeyS');
  await expect.poll(y).toBeGreaterThan(475);
  await page.keyboard.up('KeyS');
  await expect(reminder).toBeHidden();
  await page.keyboard.down('KeyW');
  await expect(reminder).toBeVisible();
  await page.keyboard.up('KeyW');
  await page.keyboard.up('Shift');
  await page.keyboard.press('KeyM');
  await expect(reminder).toBeHidden();
  await page.keyboard.press('KeyM');
  await expect(reminder).toBeVisible();
  await expect(page.getByTestId('character-status')).toContainText('步行');
  await reminder.click();
  await expect(reminder).toBeHidden();
});
