/**
 * 演示数据（百团大战场景）。
 *
 * ⚠️ 全部为占位示例，不是真实校园信息。真实社团与活动内容经核验后另行替换。
 */
import type { PublicContentSnapshot } from '../types';

export function sampleSnapshot(): PublicContentSnapshot {
  return {
    schemaVersion: 1,
    revision: 0,
    clubs: [
      {
        id: 'club-shelian',
        name: '学生社团联合会',
        category: '学生组织',
        summary: '统筹全校社团招新与百团大战等大型活动的学生组织。',
        campusIds: ['yuelushan', 'lunan', 'xiaoxiang'],
        links: [{ label: '官方公众号', url: 'https://example.com/shelian' }],
      },
      {
        id: 'club-robot',
        name: '机器人协会',
        category: '科技学术',
        summary: '面向机器人竞赛与嵌入式开发的学术社团。',
        campusIds: ['yuelushan', 'xiaoxiang'],
        links: [{ label: '协会主页', url: 'https://example.com/robot' }],
      },
      {
        id: 'club-photo',
        name: '学生摄影协会',
        category: '文化艺术',
        summary: '校园摄影创作与交流平台。',
        campusIds: ['yuelushan', 'lunan', 'xiaoxiang'],
        links: [],
      },
      {
        id: 'club-debate',
        name: '辩论队',
        category: '文化艺术',
        summary: '校内外辩论赛备赛与训练。',
        campusIds: ['yuelushan'],
        links: [],
      },
      {
        id: 'club-hanfu',
        name: '汉服社',
        category: '文化艺术',
        summary: '传统服饰展示与文化交流。',
        campusIds: ['xiaoxiang'],
        links: [{ label: '社团微博', url: 'https://example.com/hanfu' }],
      },
      {
        id: 'club-football',
        name: '足球协会',
        category: '体育竞技',
        summary: '组织校内足球友谊赛与训练。',
        campusIds: ['lunan', 'xiaoxiang'],
        links: [],
      },
      {
        id: 'club-music',
        name: '音乐社',
        category: '文化艺术',
        summary: '乐队排练、草地音乐会与演出。',
        campusIds: ['xiaoxiang'],
        links: [],
      },
    ],
    activities: [
      {
        id: 'act-opening',
        name: '百团大战开幕式',
        organizerClubId: 'club-shelian',
        category: '学生组织',
        startsAt: '2026-09-24T01:00:00Z',
        endsAt: '2026-09-24T02:30:00Z',
        campusId: 'xiaoxiang',
        venue: '副场中央舞台',
        description: '百团大战启动仪式与社团风采展示。',
        links: [],
      },
      {
        id: 'act-robot',
        name: '机器人嘉年华展示',
        organizerClubId: 'club-robot',
        category: '科技学术',
        startsAt: '2026-09-24T03:00:00Z',
        endsAt: '2026-09-24T08:00:00Z',
        campusId: 'xiaoxiang',
        venue: '副场东侧 A 区摊位',
        description: '机器人现场演示与招新答疑。',
        links: [{ label: '活动详情', url: 'https://example.com/robot-show' }],
      },
      {
        id: 'act-photo-expo',
        name: '百团大战·摄影作品展',
        organizerClubId: 'club-photo',
        category: '文化艺术',
        startsAt: '2026-09-26T00:00:00Z',
        endsAt: '2026-09-26T15:59:00Z',
        campusId: 'xiaoxiang',
        venue: '副场西侧展板长廊',
        description: '校园摄影作品展与入社咨询。',
        links: [],
      },
      {
        id: 'act-debate',
        name: '招新辩论表演赛',
        organizerClubId: 'club-debate',
        category: '文化艺术',
        startsAt: '2026-09-27T06:00:00Z',
        endsAt: '2026-09-27T08:00:00Z',
        campusId: 'xiaoxiang',
        venue: '副场中央舞台',
        description: '辩论队招新表演赛，现场可报名。',
        links: [],
      },
      {
        id: 'act-hanfu',
        name: '汉服走秀',
        organizerClubId: 'club-hanfu',
        category: '文化艺术',
        startsAt: '2026-09-27T08:00:00Z',
        endsAt: '2026-09-27T09:00:00Z',
        campusId: 'xiaoxiang',
        venue: '副场中央舞台',
        description: '传统服饰走秀展示。',
        links: [],
      },
      {
        id: 'act-concert',
        name: '草地音乐会',
        organizerClubId: 'club-music',
        category: '文化艺术',
        startsAt: '2026-09-28T11:00:00Z',
        endsAt: '2026-09-28T13:00:00Z',
        campusId: 'xiaoxiang',
        venue: '副场草坪',
        description: '乐队现场演出，欢迎围观。',
        links: [{ label: '曲目单', url: 'https://example.com/concert' }],
      },
      {
        id: 'act-football',
        name: '五人制足球友谊赛',
        organizerClubId: 'club-football',
        category: '体育竞技',
        startsAt: '2026-09-29T07:00:00Z',
        endsAt: '2026-09-29T09:00:00Z',
        campusId: 'xiaoxiang',
        venue: '副场足球场',
        description: '社团招新友谊赛，可现场组队。',
        links: [],
      },
    ],
  };
}
